### ISSUE TITLE
File examples/README.md is missing

### ISSUE THREAD

**Issue by fyurisich** [dev-harbour/hb-nuklear#1]
Hi, Rafał Jopek, great job!

Please, take note that the file examples/README.md is missing.

Regards and many thanks for this contribution to the Harbor community.

**Comment by rjopek** [comment]
Hi,

[README.md](https://github.com/dev-harbour/hb-nuklear/tree/main/examples)

Projects on GitHub are created at the repository owner's level (organization or user) and can be linked to a repository's Projects tab. Projects are suitable for cross-repository development efforts such as feature work, complex product roadmaps or even Issue triage.

[discussions](https://github.com/dev-harbour/hb-nuklear/discussions)
